#!/usr/bin/env bash
# setup.sh — provision (or refresh) the single llm-wiki zk notebook.
#
# This script *installs* llm-wiki's deployable artifacts into the notebook; it
# does not author them. Each artifact is its own file in THIS skill
# (llm-wiki-init, which owns deployment), and that file is the source of truth:
#   assets/config.toml  → $notebook/.zk/config.toml           (the verb aliases)
#   assets/default.md   → $notebook/.zk/templates/default.md  (the note template)
#   scripts/walk.sh     → $notebook/.zk/walk.sh               (the human walker)
# Nothing here is generated by the shell, so no quoting/expansion rule can
# corrupt an artifact in transit (the aliases contain literal `$1` / `$@` /
# `$ZK_NOTEBOOK_DIR`, which a heredoc could silently eat). llm-wiki-base holds
# the *model* — what the verbs mean and when to use them; this skill holds the
# payload and deploys it.
#
# The llm-wiki operation skills run it (via
# `bash "<llm-wiki-init>/scripts/setup.sh"`) before any read/write, and a human
# runs it directly after a `git pull` to redeploy — llm-wiki-init's SKILL.md is
# the front door for that.
#
# IDEMPOTENT by construction: it does not diff or patch, it overwrites every
# artifact on every run, so any number of runs converges to the same state.
# `zk init` is the only conditional step (only when `.zk` is absent). Re-running
# is always safe and is how existing notebooks pick up new aliases. NOTE: the
# deployed config and template are skill-owned — a hand edit to the deployed
# copy is overwritten on the next run by design; edit the assets/ file instead.
set -euo pipefail

# Self-locate: the artifacts live in this same skill (assets/ and scripts/), so
# setup needs no externally-supplied dir. Resolves correctly however it is run.
script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
base_dir="$(cd "$script_dir/.." && pwd)"

wiki="${XDG_DATA_HOME:-$HOME/.local/share}/llm-wiki"
if [ ! -d "$wiki/.zk" ]; then
  mkdir -p "$wiki"
  zk --no-input init "$wiki" >/dev/null
fi
mkdir -p "$wiki/.zk/templates"   # zk init makes this, but be robust if it's gone

install -m 0644 "$base_dir/assets/config.toml" "$wiki/.zk/config.toml"
install -m 0644 "$base_dir/assets/default.md"  "$wiki/.zk/templates/default.md"
install -m 0755 "$script_dir/walk.sh"          "$wiki/.zk/walk.sh"

printf 'llm-wiki notebook ready at %s\n' "$wiki"
